name: Prettier code formatter

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install Prettier
        run: npm install --save-dev --save-exact prettier @shopify/prettier-plugin-liquid

      - name: Run Prettier
        run: npx prettier . --write

      - name: Commit formatted files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Format files with Prettier
